[[constraint]]
  name = "github.com/olivere/elastic"

[[constraint]]
  name = "gitlab.com/proemergotech/geb-client-go"
  source = "git@gitlab.com:proemergotech/geb-client-go.git"

[prune]
  unused-packages = true
  go-tests = true
